services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-base1cine.alwaysdata.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: base1cine_olympics
      - key: DB_USERNAME
        value: base1cine_admin
      - key: DB_PASSWORD
        value: contrasena_1234
